tasks:
- dataset_path: bdg-2_bear
  name: BDG2-Bear
  freq: '1H'
- dataset_path: bdg-2_rat
  name: BDG2-Rat
  freq: '1H'
- dataset_path: borealis
  name: borealis
  freq: '1H'
- dataset_path: covid19_energy
  name: Covid19
  freq: '1H'
- dataset_path: gfc12_load
  name: gfc12
  freq: '1H'
- dataset_path: hog
  name: hog
  freq: '1H'
- dataset_path: ideal
  name: ideal
  freq: '1H'
- dataset_path: kdd2022
  name: kdd2022
  freq: '10T'
- dataset_path: oikolab_weather
  name: oikolab
  freq: '1H'
- dataset_path: pdb
  name: PDB
  freq: '1H'
- dataset_path: pedestrian_counts
  name: pedestrian_counts
  freq: '1H'
- dataset_path: PEMS_BAY
  name: PEMS_BAY
  freq: '5T'
- dataset_path: PEMS03
  name: PEMS03
  freq: '5T'
- dataset_path: SHMETRO
  name: SHMETRO
  freq: '15T'
- dataset_path: traffic_hourly
  name: Traffic
  freq: '1H'
- dataset_path: ett1/H
  name: ETTh1
  freq: '1H'
- dataset_path: ett2/H
  name: ETTh2
  freq: '1H'
- dataset_path: ett1/15T
  name: ETTm1
  freq: '15T'
- dataset_path: ett2/15T
  name: ETTm2
  freq: '15T'
- dataset_path: jena_weather/10T
  name: JenaWeather10T
  freq: '10T'
- dataset_path: jena_weather/H
  name: JenaWeatherH
  freq: '1H'
- dataset_path: M_DENSE/H
  name: M_DENSE
  freq: '1H'
- dataset_path: LOOP_SEATTLE/5T
  name: LoopSeattle5T
  freq: '5T'
- dataset_path: LOOP_SEATTLE/H
  name: LoopSeattleH
  freq: '1H'
- dataset_path: solar/H
  name: Solar
  freq: '1H'
- dataset_path: era5_geopotential_small
  name: ERA5_Geopotential
  freq: '1H'
- dataset_path: era5_humidity_small
  name: ERA5_Humidity
  freq: '1H'
- dataset_path: era5_temperature_small
  name: ERA5_Temp
  freq: '1H'
- dataset_path: era5_wind_speed_small
  name: ERA5_WindSpeed
  freq: '1H'
- dataset_path: enedis_ldm_small/
  name: EnedisSmall
  freq: '30T'
- dataset_path: london_small/
  name: LondonSmall
  freq: '30T'
- dataset_path: spain_energy
  name: SpainEnergy
  freq: '1H'
- dataset_path: weather
  name: Weather
  freq: '1H'

