tasks:
- dataset_path: occitanie2021
  name: Occitanie2021
  freq: '1H'
  target_channel: 7
  covar_channel: [4]
- dataset_path: paca2021
  name: PACA2021
  freq: '1H'
  target_channel: 7
  covar_channel: [4]
- dataset_path: hdf2021
  name: HdF2021
  freq: '1H'
  target_channel: 6
  covar_channel: [0]
- dataset_path: grandest2021
  name: GrandEst2021
  freq: '1H'
  target_channel: 6
  covar_channel: [0]
- dataset_path: France2021
  name: France2021
  freq: '30T'
  target_channel: 0
  covar_channel: [3]
- dataset_path: France2022
  name: France2022
  freq: '30T'
  target_channel: 0
  covar_channel: [3]